"""Defaults for the single-sound oto.ini editor."""

SUPPORTED_AUDIO_EXTENSIONS = {".wav"}
OTO_FILE_NAME = "oto.ini"
SILENCE_PEAK_THRESHOLD = 0.005
DEFAULT_OFFSET = 0.0
DEFAULT_CONSONANT = 0.0
DEFAULT_CUTOFF = 0.0
DEFAULT_PREUTTERANCE = 0.0
DEFAULT_OVERLAP = 0.0
