"""Application defaults for AutoOtoMaker."""

DEFAULT_SAMPLE_RATE = 44100
DEFAULT_FIXED_MS = 120.0
DEFAULT_PREUTTERANCE_MS = 60.0
DEFAULT_OVERLAP_MS = 30.0
DEFAULT_BLANK_MS = 80.0
SUPPORTED_AUDIO_EXTENSIONS = {".wav"}
SUPPORTED_JSON_EXTENSIONS = {".json"}
